apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: portfolio

resources:
- cert.yaml
- gw.yaml
- vs.yaml
- sa.yaml
- deployment.yaml
- svc.yaml
  
images:
- name: crchiran-portfolio
  newName: ghcr.io/crchiran/crchiran-portfolio
  newTag: prod-79572f3-20260619-0303-10
